name: turbo_zip
description: Library containing various algorithms for encoding and decoding text and numbers
version: 1.0.1
repository: https://github.com/AdityaMotale/turbo_zip

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: